
-- 1
SELECT *
FROM KHACHHANG
WHERE DIA_CHI = 'Tân Bình'
-- 2
SELECT MA_KH ,TEN_KH, DIA_CHI, EMAIL
FROM KHACHHANG
WHERE DT IS NULL
-- 3
SELECT MA_KH,TEN_KH,DIA_CHI
FROM KHACHHANG
WHERE DT IS NULL AND EMAIL IS NULL
-- 4
SELECT *
FROM KHACHHANG
WHERE DT IS NOT NULL AND EMAIL IS NOT NULL
-- 5
SELECT MA_VT, TEN_VT, GIA_MUA
FROM VATTU
WHERE DON_VI_TINH = 'Cái';
-- 6
SELECT MA_VT, TEN_VT, DON_VI_TINH, GIA_MUA
FROM VATTU
WHERE GIA_MUA > 25000
-- 7 ======================== chua lam xong ===============
SELECT A.MA_VT, A.TEN_VT, A.DON_VI_TINH, A.GIA_MUA
FROM VATTU AS A
WHERE A.TEN_VT LIKE '%Gạch%'
-- 8
SELECT MA_VT, TEN_VT, DON_VI_TINH, GIA_MUA
FROM VATTU
WHERE GIA_MUA BETWEEN 20000 AND 40000
-- 9
SELECT B.MA_HD, B.Ngay, A.TEN_KH, A.DIA_CHI, A.DT
FROM KHACHHANG AS A
INNER JOIN HOADON AS B
ON A.MA_KH = B.MA_KH
-- 10
SELECT B.MA_HD, A.TEN_KH, A.DIA_CHI, A.DT
FROM KHACHHANG AS A
INNER JOIN HOADON AS B
ON A.MA_KH = B.MA_KH
WHERE B.Ngay = '2010-5-25'
-- 11
SELECT B.MA_HD, B.Ngay, A.TEN_KH, A.DIA_CHI, A.DT
FROM KHACHHANG AS A
INNER JOIN HOADON AS B
ON A.MA_KH = B.MA_KH
WHERE YEAR(Ngay) = 2010 AND MONTH(Ngay) = 6
-- 12
SELECT A.TEN_KH, A.DIA_CHI, A.DT
FROM KHACHHANG AS A
INNER JOIN HOADON AS B
ON A.MA_KH = B.MA_KH
WHERE YEAR(Ngay) = 2010 AND MONTH(Ngay) = 6
-- 13
SELECT A.TEN_KH, A.DIA_CHI, A.DT
FROM KHACHHANG AS A
WHERE A.MA_KH NOT IN (
             SELECT B.MA_KH
			 FROM HOADON AS B
			 WHERE YEAR(B.Ngay) = 2010 AND MONTH(B.Ngay) = 6
			 )
-- 14
SELECT B.MA_HD, B.MA_VT, A.TEN_VT, A.DON_VI_TINH, B.GIA_BAN, A.GIA_MUA, B.SL,
       A.GIA_MUA * SL AS TRIGIAMUA, B.GIA_BAN * SL AS TRIGIABAN
FROM VATTU AS A
INNER JOIN CHITIETHOADON AS B
ON A.MA_VT = B.MA_VT
-- 15
SELECT B.MA_HD, B.MA_VT, A.TEN_VT, A.DON_VI_TINH, B.GIA_BAN, A.GIA_MUA, B.SL,
       A.GIA_MUA * SL AS TRIGIAMUA, B.GIA_BAN * SL AS TRIGIABAN
FROM VATTU AS A
INNER JOIN CHITIETHOADON AS B
ON A.MA_VT = B.MA_VT
WHERE GIA_BAN >= GIA_MUA
-- 16
SELECT B.MA_HD, B.MA_VT, A.TEN_VT, A.DON_VI_TINH, B.GIA_BAN, A.GIA_MUA, B.SL,
       A.GIA_MUA * SL AS TRIGIAMUA, B.GIA_BAN * SL AS TRIGIABAN,
	   CASE
	   WHEN B.SL > 100 THEN 10.0
	   ELSE 0.0
	   END AS KHUYEN_MAI
FROM VATTU AS A
INNER JOIN CHITIETHOADON AS B
ON A.MA_VT = B.MA_VT
-- 17
SELECT B.TEN_VT
FROM CHITIETHOADON AS A
INNER JOIN VATTU AS B
ON A.MA_VT = B.MA_VT
WHERE A.SL IS NULL -- HÊN XUI
-- 18
SELECT B.MA_HD, B.Ngay, D.TEN_KH, D.DIA_CHI, D.DT, C.TEN_VT, C.DON_VI_TINH, C.GIA_MUA, A.GIA_BAN, A.SL,
       A.GIA_BAN * A.SL AS TRIGIAMUA, C.GIA_MUA * A.SL AS TRIGIABAN
FROM CHITIETHOADON AS A
INNER JOIN HOADON AS B
ON A.MA_HD = B.MA_HD
INNER JOIN VATTU AS C
ON A.MA_VT = C.MA_VT
INNER JOIN KHACHHANG AS D
ON D.MA_KH = B.MA_KH
-- 19
SELECT B.MA_HD, B.Ngay, D.TEN_KH, D.DIA_CHI, D.DT, C.TEN_VT, C.DON_VI_TINH, C.GIA_MUA, A.GIA_BAN, A.SL,
       A.GIA_BAN * A.SL AS TRIGIAMUA, C.GIA_MUA * A.SL AS TRIGIABAN
FROM CHITIETHOADON AS A
INNER JOIN HOADON AS B
ON A.MA_HD = B.MA_HD
INNER JOIN VATTU AS C
ON A.MA_VT = C.MA_VT
INNER JOIN KHACHHANG AS D
ON D.MA_KH = B.MA_KH
WHERE YEAR(Ngay) = 2010 AND MONTH(Ngay) = 5
-- 20
SELECT B.MA_HD, B.Ngay, D.TEN_KH, D.DIA_CHI, D.DT, C.TEN_VT, C.DON_VI_TINH, C.GIA_MUA, A.GIA_BAN, A.SL,
       A.GIA_BAN * A.SL AS TRIGIAMUA, C.GIA_MUA * A.SL AS TRIGIABAN
FROM CHITIETHOADON AS A
INNER JOIN HOADON AS B
ON A.MA_HD = B.MA_HD
INNER JOIN VATTU AS C
ON A.MA_VT = C.MA_VT
INNER JOIN KHACHHANG AS D
ON D.MA_KH = B.MA_KH
WHERE YEAR(B.Ngay) = 2010 AND  MONTH(B.Ngay) IN (1, 2, 3)
-- 21
SELECT A.MA_HD, B.Ngay, D.TEN_KH, D.DIA_CHI, SUM(A.GIA_BAN * A.SL) AS TONGHOADON
FROM CHITIETHOADON AS A
INNER JOIN HOADON AS B
ON A.MA_HD = B.MA_HD
INNER JOIN VATTU AS C
ON A.MA_VT = C.MA_VT
INNER JOIN KHACHHANG D
ON D.MA_KH = B.MA_KH
GROUP BY A.MA_HD, B.Ngay, D.TEN_KH, D.DIA_CHI
-- 22
SELECT TOP 1 A.MA_HD, B.Ngay, D.TEN_KH, D.DIA_CHI, SUM(A.GIA_BAN * A.SL) AS TONGHOADON
FROM CHITIETHOADON AS A
INNER JOIN HOADON AS B
ON A.MA_HD = B.MA_HD
INNER JOIN VATTU AS C
ON A.MA_VT = C.MA_VT
INNER JOIN KHACHHANG D
ON D.MA_KH = B.MA_KH
GROUP BY A.MA_HD, B.Ngay, D.TEN_KH, D.DIA_CHI
ORDER BY TONGHOADON DESC 
-- 23
SELECT TOP 1 A.MA_HD, B.Ngay, D.TEN_KH, D.DIA_CHI, SUM(A.GIA_BAN * A.SL) AS TONGHOADON
FROM CHITIETHOADON AS A
INNER JOIN HOADON AS B
ON A.MA_HD = B.MA_HD
INNER JOIN VATTU AS C
ON A.MA_VT = C.MA_VT
INNER JOIN KHACHHANG D
ON D.MA_KH = B.MA_KH
WHERE YEAR(Ngay) = 2010 AND MONTH(Ngay) = 5
GROUP BY A.MA_HD, B.Ngay, D.TEN_KH, D.DIA_CHI
ORDER BY TONGHOADON DESC 
-- 24 
SELECT A.TEN_KH ,COUNT(B.MA_HD) AS SO_LUONG_HOA_DON
FROM KHACHHANG AS A
INNER JOIN HOADON AS B
ON A.MA_KH = B.MA_KH
GROUP BY A.TEN_KH
-- 25
-- ///////// KO BIT LAM 
-- 26
SELECT TOP 1 A.TEN_KH ,COUNT(B.MA_HD) AS SO_LUONG_HOA_DON
FROM KHACHHANG AS A
INNER JOIN HOADON AS B
ON A.MA_KH = B.MA_KH
GROUP BY A.TEN_KH
ORDER BY SO_LUONG_HOA_DON DESC
-- 27
SELECT TOP 1 A.MA_KH, A.DIA_CHI, A.DT, A.EMAIL, A.TEN_KH, SUM(C.SL) AS MUA_NHIEU_NHAT
FROM KHACHHANG AS A
INNER JOIN HOADON AS B
ON A.MA_KH = B.MA_KH
INNER JOIN CHITIETHOADON AS C
ON B.MA_HD = C.MA_HD
GROUP BY A.MA_KH, A.DIA_CHI, A.DT, A.EMAIL, A.TEN_KH
ORDER BY MUA_NHIEU_NHAT DESC
-- 28
SELECT TOP 1 A.MA_VT, A.TEN_VT, A.DON_VI_TINH, A.GIA_MUA, A.SO_LUONG_TON, 
       COUNT(B.MA_VT) AS NHIEU_HOA_DON_NHAT
FROM VATTU AS A
INNER JOIN CHITIETHOADON AS B
ON A.MA_VT = B.MA_VT
GROUP BY A.MA_VT, A.TEN_VT, A.DON_VI_TINH, A.GIA_MUA, A.SO_LUONG_TON
ORDER BY NHIEU_HOA_DON_NHAT DESC
-- 29
SELECT TOP 1 A.MA_VT, A.TEN_VT, A.DON_VI_TINH, A.GIA_MUA, A.SO_LUONG_TON, 
       SUM(B.SL) AS HANG_BAN_NHIEU_NHAT
FROM VATTU AS A
INNER JOIN CHITIETHOADON AS B
ON A.MA_VT = B.MA_VT
GROUP BY A.MA_VT, A.TEN_VT, A.DON_VI_TINH, A.GIA_MUA, A.SO_LUONG_TON
ORDER BY HANG_BAN_NHIEU_NHAT DESC
-- 30
SELECT A.MA_KH, A.TEN_KH, A.DIA_CHI, COUNT(C.MA_HD) AS SO_LUONG_HOA_DON
FROM KHACHHANG AS A
INNER JOIN HOADON AS B
ON A.MA_KH = B.MA_KH 
INNER JOIN CHITIETHOADON AS C
ON B.MA_HD = C.MA_HD
GROUP BY  A.MA_KH, A.TEN_KH, A.DIA_CHI












